add_custom_target(examples_cpp)
add_custom_target(examples_fortran)
add_custom_target(examples_simple_advector)
add_custom_target(examples_simple_paraboloid_advector)
add_custom_target(examples_advector)
add_custom_target(examples_paraboloid_advector)
add_custom_target(examples_variant_advector)
add_custom_target(examples_implicit_surface_reconstruction)

include(${PROJECT_SOURCE_DIR}/cmake/Utils/IRLAddExample.cmake)

add_subdirectory("./fortran")
add_subdirectory("./cpp")
add_subdirectory("./simple_advector")
add_subdirectory("./simple_paraboloid_advector")
add_subdirectory("./advector")
add_subdirectory("./paraboloid_advector")
add_subdirectory("./variant_advector")
add_subdirectory("./implicit_surface_reconstruction")

if(IRL_BUILD_AMREX_INTERFACE)
    add_custom_target(examples_amrex_advector)
    add_subdirectory("./amrex_advector")
endif()