add_custom_target(examples_cpp)
add_custom_target(examples_fortran)
add_custom_target(examples_simple_advector)
add_custom_target(examples_simple_paraboloid_advector)
add_custom_target(examples_advector)
add_custom_target(examples_paraboloid_advector)
add_custom_target(examples_vtk_output)
add_custom_target(examples_ml_classification)
add_custom_target(examples_ml_data_vtk)
add_custom_target(examples_ml_minimal_classifier_notorch)
add_custom_target(examples_ml_synthetic_test_cases)
add_custom_target(examples_vtk_reader)
add_custom_target(examples_variant_advector)

include(${PROJECT_SOURCE_DIR}/cmake/Utils/IRLAddExample.cmake)

add_subdirectory("./fortran")
add_subdirectory("./cpp")
add_subdirectory("./simple_advector")
add_subdirectory("./simple_paraboloid_advector")
add_subdirectory("./advector")
add_subdirectory("./paraboloid_advector")
add_subdirectory("./vtk_output")
add_subdirectory("./ml_classification")
add_subdirectory("./ml_data_vtk")
add_subdirectory("./ml_minimal_classifier_notorch")
add_subdirectory("./vtk_reader")
add_subdirectory("./variant_advector")